# spring Configuration
spring:
   application:
      name: emaillist

      
---
# common spring Configuration

spring:
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/assets/
   
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false
     
mybatis:
   config-location: classpath:mybatis/configuration.xml

# logging
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
      console: "Console: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n "
   level:
      root: INFO


# Server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: utf-8
         enabled: true
         
---
# devel common spring Configuration
spring:
   config:
      activate:
         on-profile: development
      
   
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
   
   # mvc
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/assets/
   
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false
# production profile: spring boot configuration

   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.92:3307/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
# server
server:
   port: 8088
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         






         


